name: Update DROP Supply

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build supply.json
        run: npm run build

      - name: Commit and push changes if any
        run: |
          if [[ -n "$(git status --porcelain docs/supply.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/supply.json
            git commit -m "chore: auto-update supply.json"
            git pull --rebase origin main
            git push --force-with-lease
          else
            echo "No changes to commit."
          fi
